In [17]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = [[100, 0.01],
        [8, 0.05],
        [50, 0.005]]
        
np_data = np.asarray(data)

scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)
print(scaled)

[[1.         0.11111111]
 [0.         1.        ]
 [0.45652174 0.        ]]


In [26]:
from statistics import mean, pstdev

def std_feature(data):
    baris_data = data.shape[0]
    kolom_data = data.shape[1]

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            data[i][j] = (data[i][j] - mean(data[:,j])) / pstdev(data[:,j])

    return data

data = [[100, 0.001],
        [8, 0.05],
        [50, 0.005],
        [88, 0.07],
        [4, 0.1]]


data = np.asarray(data)

std_data = std_feature(data)
std_data

array([[ 1.26398112, -1.16389967],
       [-0.65623116,  0.48622176],
       [ 0.6102111 ,  0.18921441],
       [ 1.99807462,  0.23476602],
       [ 1.65186847,  0.22506085]])

In [27]:
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler()

std_data = ss_scaler.fit_transform(data)
std_data

array([[ 0.31019162, -1.96754253],
       [-1.74088681,  0.83573983],
       [-0.38813407,  0.33117364],
       [ 1.094315  ,  0.40855827],
       [ 0.72451425,  0.39207079]])

In [29]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

oe = [['POLINEMA'],
    ['PENS'],
    ['PIN'],
    ['PNP'],
    ['POLBAN']]

ord_oe = OrdinalEncoder().fit_transform(oe)
ohe_oe = OneHotEncoder().fit_transform(oe)
ohe_oe.toarray()

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [34]:
corpus = [
            'the house had a tiny little mouse',
            'the cat saw the mouse',
            'the mouse ran away from the house',
            'the cat finally ate the mouse',
            'the end of the mouse story'
]

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(response.todense())

['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse', 'ran', 'saw', 'story', 'tiny']
[[0.         0.         0.         0.         0.         0.4755751
  0.58946308 0.28088232 0.         0.         0.         0.58946308]
 [0.         0.         0.58873218 0.         0.         0.
  0.         0.34771471 0.         0.72971837 0.         0.        ]
 [0.         0.58946308 0.         0.         0.         0.4755751
  0.         0.28088232 0.58946308 0.         0.         0.        ]
 [0.58946308 0.         0.4755751  0.         0.58946308 0.
  0.         0.28088232 0.         0.         0.         0.        ]
 [0.         0.         0.         0.67009179 0.         0.
  0.         0.31930233 0.         0.         0.67009179 0.        ]]
